name: real_estate_empire
description: A mobile real estate tycoon idle simulator game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Local Storage
  sqflite: ^2.2.8+4
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  
  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  
  # Utilities
  intl: ^0.18.1
  collection: ^1.17.1
  uuid: ^3.0.7
  
  # Animations
  flutter_animate: ^4.1.1+1
  
  # Sound
  audioplayers: ^4.0.1
  
  # Ads & Monetization (for later)
  # in_app_purchase: ^3.1.5
  # google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/data/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700